name: Auto Video Creator

on:
  schedule:
    - cron: '0 8 * * *'  # كل يوم الساعة 8 صباحًا
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install moviepy==1.0.3 Pillow==9.5.0
          pip install imageio imageio-ffmpeg decorator proglog
          pip install openai elevenlabs requests pytube pysrt
          pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
          pip install git+https://github.com/openai/whisper.git
          pip install yt-dlp

      - name: Run main script
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          API_VIDEO_KEY: ${{ secrets.API_VIDEO_KEY }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
        run: python main.py
